### ISSUE TITLE
Gcode Prompt Output Truncated

### ISSUE THREAD

**Issue by dmbaio** [Ankermgmt/ankermake-m5-protocol#48]
As the title says, the output returned from the code prompt, at least for M503 to read settings, seems to grab a section of the middle of the output instead of showing the full output.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/59879282/231342488-5454b4a1-e0a9-4b53-8853-71ade6dfe0be.png">

**Comment by chrivers** [comment]
Hello dmbaio :)

Thanks for reporting this error.

I've looked into it, and it seems like this is a limitation of the printer firmware. It's not clear if there's any way around this, but it doesn't look like it.

We are decoding and displaying pretty much exactly what we receive over MQTT, so unless there's some way to indicate that we want/can handle larger responses, this doesn't seem to be possible.

Which is, of course, a real shame, since it limits what we can do with this.

I'll keep this ticket open for now, until we figure out definitively what's going on.

**Comment by chrivers** [comment]
Everything I've looked into, shows that this is, unfortunately, a firmware problem in the printer. We simply cannot get more output than this, until they fix the firmware.

I hope they will eventually fix or improve it, but until they do, there's nothing we can do to fix it. The data just isn't there :-(

I'll close this for now, since it's out of our hands.
